docs(samples): updated samples code to use async await
praveenqlogic/nodejs-tasks pull request #1
Opened 2018-11-20 15:02 UTC by praveenqlogic

Fixes googleapis/google-cloud-node#2869 (it's a good idea to open an issue first for discussion)
Fixes https://github.com/googleapis/nodejs-tasks

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

2018-11-20 16:47 UTC, ajaaym requested changes

2018-11-20 16:47 UTC, ajaaym commented on samples/createTask.js
> +main().catch(console.error);
this is not correct you dont need to have this.

2018-11-20 17:26 UTC, praveenqlogic commented on samples/createTask.js
> +main().catch(console.error);
removed!

2018-11-23 07:04 UTC, praveenqlogic commented
@ajaaym Hi, Please review the code changes and let me know if any changes required, need approval to create PR!

2018-12-11 17:02 UTC, merged